backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "about.html"
        label: "About"
        name: "about"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "custom-homes.html"
        label: "Custom Homes"
        name: "custom_homes"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "renovations.html"
        label: "Renovations"
        name: "renovations"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "wellness-spaces.html"
        label: "Wellness Spaces"
        name: "wellness_spaces"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "healthy-homes.html"
        label: "Healthy Homes"
        name: "healthy_homes"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "process.html"
        label: "Process"
        name: "process"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "blog.html"
        label: "Journal / Blog"
        name: "blog"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Page HTML", name: "body", widget: "code", output_code_only: true, default_language: "html"}
